// Base de dados do Ciclo de Desenvolvimento e Evolução — ZERADA.
// Cadastros, sincronizados via Supabase (nuvem) quando configurado, com cache local (localStorage):
//  - gestores: cadastrados pelo RH (Nome, Cargo, Diretoria, Regional, Unidade, Setor, Departamento, login)
//  - funcionarios: quadro de colaboradores, vinculados a um gestor (gestorId)
//  - ciclos: cada ciclo de desenvolvimento vinculado a um funcionário
//  - auditLog: histórico de ações (quem criou/editou/excluiu o quê)
//  - rhAuth: credencial única da administração do RH
//  - catalogos: listas suspensas (Regional, Diretoria, Departamento, Setor, Unidade) — o RH pode
//    cadastrar novos itens direto no formulário, e eles ficam salvos aqui para todos usarem depois.
window.CICLO_DATA = {
  ano: "2026",
  gestores: [],
  funcionarios: [],
  ciclos: [],
  auditLog: [],
  rhAuth: null,
  catalogos: {
    regionais: ["Adm & Finanças", "Azul Agro", "Byd Bsb", "Byd Es", "Byd Go", "Byd Grande Bh", "Byd Leste De Minas", "Byd Norte De Minas", "Byd Sul De Minas", "Byd Triangulo Mg", "Byd Zona Da Mata", "Denza Grande Bh", "Godrive", "Jeep/Ram Es", "Jeep/Ram Mg", "Jeep/Ram Rj", "Mercedes Caminhões Es", "Mercedes Caminhões Sul", "Pneus Caminhões Es", "Pneus Caminhões Sul", "Toyota Bsb", "Toyota Es", "Toyota Grande Bh", "Toyota Leste De Minas", "Toyota Rj", "Toyota Triangulo Mg", "Toyota Zona Da Mata", "Vitoria Motors Mbb"],
    diretorias: ["Adm E Financas", "Aguia Branca Seminovos", "Azul Agro", "Estrategia De Negocios", "Gef", "Godrive", "Inteligencia De Mercado", "Kuruma Osaka Kyoto", "Savana", "Tech", "Venda Direta", "Vitoria Diesel", "Vitoria Motors Byd", "Vitoria Motors Jeep Ram", "Vitoria Motors Mbb"],
    departamentos: ["Administração", "Controladoria", "Diretoria", "Godrive", "Governança E Relações Jurídicas", "Oficina", "Peças E Acessórios", "Pessoas E Cultura", "Pn/Pneus", "Recapagem Michelin", "Veículos Novos", "Veículos Ônibus", "Veículos Sprinter", "Veículos Usados"],
    setores: ["Acessórios", "Adm Central Acessórios", "Adm Central De Vendas", "Adm Central De Vendas Diretas", "Adm Central Pós Venda", "Adm Central Vendas F&i", "Adm Central Vu", "Adm Colatina", "Adm De Truck Center", "Adm Funilaria", "Adm Lead Center", "Adm Oficina Colatina", "Adm Recapagem", "Adm Truck Center Linhares", "Adm Truck Center Serra", "Admc Corretora", "Admc Inteligencia E Cx", "Admc Relacionamento", "Admcv Marketing", "Administr. Oficina", "Administração Pds", "Administrativo Regional", "Assistência Técnica", "Business Partners", "Centro Treinamento", "Comunicação Interna", "Contabilidade", "Contas A Pagar", "Contas A Receber", "Departamento Pessoal", "Desenvolvimento Humano Organizacional", "Diretoria", "Estruturas Fisicas", "Fiscal", "Funil. Pint. Lantern.", "Garantia", "Gef", "Grandes Clientes", "Jurídico, Riscos & Compliance", "Locação Go Drive", "Mecânica", "Mecânica Caminhões", "Pds Carapina", "Peças", "Peças Balcão", "Peças Balcão Grandes Clientes", "Peças Mecânica", "Peças Telemarketing", "People Analytics", "People Experience E Inovação", "Planejamento", "Plm", "Pneus", "Pneus Linhares", "Pneus Serra", "Produção Recapagem", "Recrutamento E Seleção", "Remuneração E Beneficios", "Remuneração E Performance", "Serviços Acessórios", "Sesmt", "Societário", "Suprimentos", "Tech", "Truck Center", "Truck Center Linhares", "Truck Center Serra", "Veículos Caminhões", "Veículos Lexus", "Veículos Novos", "Veículos Ônibus", "Veículos Sprinter", "Veículos Usados", "Venda Direta", "Venda Direta Corporativa", "Vendas F&i", "Vendas On Line"],
    unidades: ["Ab Bh", "Ab Comércio Vitória", "Ab Contagem", "Ab Contagem 2", "Ab Energias Renovaveis", "Ab Lexus", "Ab Pampulha", "Ab Sete Lagoas", "Águia Branca Bh", "Águia Branca Linhares", "Águia Branca Vitória", "Ev Anápolis", "Ev Aparecida De Goiânia", "Ev Aparecida Seminovos", "Ev Asa Norte", "Ev Barão", "Ev Cachoeiro", "Ev Catalão Go", "Ev Denza Bh", "Ev Denza Vitória", "Ev Divinopolis", "Ev Fernando Ferrari", "Ev Goiânia", "Ev Governador Valadares", "Ev Ipatinga", "Ev Itumbiara", "Ev Jatai", "Ev Juiz De Fora", "Ev Linhares", "Ev Montes Claros", "Ev Nova Lima", "Ev Pampulha", "Ev Patos De Minas", "Ev Poços De Caldas", "Ev Pouso Alegre", "Ev Raja", "Ev Rio Verde", "Ev Serra", "Ev Sia", "Ev Uberaba", "Ev Uberlândia", "Ev Varginha", "Ev Vila Velha", "Ev Vitoria", "Kurumá Barbacena", "Kurumá Cachoeiro", "Kurumá Cariacica", "Kurumá Colatina", "Kurumá Diretoria Adm Finanças", "Kurumá Épia", "Kurumá Galpão Sia", "Kurumá Governador Valadares", "Kurumá Guarapari", "Kurumá Ipatinga", "Kurumá Itabira", "Kurumá João Naves", "Kurumá Juiz De Fora", "Kurumá Juiz Fora 2", "Kurumá Lexus Sia", "Kurumá Linhares", "Kurumá Manhuaçu", "Kurumá Muriaé", "Kurumá Patos De Minas", "Kurumá São Mateus", "Kurumá Seminovos Sia", "Kurumá Serra", "Kuruma Serra Pds", "Kurumá Sia", "Kuruma Sia Aeroporto", "Kurumá Taguatinga", "Kurumá Teófilo Otoni", "Kurumá Ubá", "Kurumá Uberaba", "Kurumá Uberlândia", "Kuruma Uberlândia Galpão", "Kurumá Venda Nova", "Kurumá Vila Velha", "Kurumá Vitória", "Savana Campo Largo", "Savana Concórdia", "Savana Curitiba", "Savana Curitiba Vans", "Savana Diretoria Adm Finanças", "Savana Guaramirim", "Savana Jaguariaíva", "Savana Joinville", "Savana Pneus Ponta Grossa", "Savana Pneus São José Dos Pinhais", "Savana Ponta Grossa", "Savana Registro Sp", "Savana São José Dos Pinhais", "Savana Telêmaco Borba", "Savana Xanxerê", "Vd Alto Taquari", "Vd Cachoeiro", "Vd Caiaponia", "Vd Cariacica", "Vd Colatina", "Vd Diretoria Adm Finanças", "Vd Itaberaí", "Vd Jatai", "Vd Linhares", "Vd Mineiros", "Vd Pneus Cachoeiro", "Vd Pneus Cariacica", "Vd Pneus Colatina", "Vd Pneus Linhares", "Vd São Miguel Do Araguaia", "Vd Uruaçu", "Vd Venda Nova", "Vitoria Motors Mbb", "Vm Cachoeiro", "Vm Colatina", "Vm Guarapari", "Vm Juiz De Fora", "Vm Linhares", "Vm Nova Friburgo", "Vm Petrópolis", "Vm Serra", "Vm Serra Galpao", "Vm Vila Velha", "Vm Vitória", "Vm Vitória Ram"],
  },
};
